"""Python strategy base class for backtesting."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field

import pandas as pd


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    symbol: str
    signal_type: str  # "buy", "sell", "hold"
    strength: float  # -1.0 to 1.0
    metadata: dict = field(default_factory=dict)


class Strategy(ABC):
    """Base class for Python trading strategies."""

    @abstractmethod
    def name(self) -> str:
        """Return the strategy name."""
        ...

    @abstractmethod
    def on_bars(self, bars: pd.DataFrame) -> list[Signal]:
        """Process a batch of bar data and return signals.

        Args:
            bars: DataFrame with OHLCV data.

        Returns:
            List of trading signals.
        """
        ...


class SMACrossStrategy(Strategy):
    """Simple Moving Average crossover strategy example."""

    def __init__(self, short_period: int = 20, long_period: int = 50):
        self.short_period = short_period
        self.long_period = long_period

    def name(self) -> str:
        return "sma-cross"

    def on_bars(self, bars: pd.DataFrame) -> list[Signal]:
        """Generate signals based on SMA crossover."""
        # TODO: Implement SMA crossover logic
        return []
