// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: marketdata.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTradesRequest) Reset() {
	*x = StreamTradesRequest{}
	mi := &file_marketdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTradesRequest) ProtoMessage() {}

func (x *StreamTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTradesRequest.ProtoReflect.Descriptor instead.
func (*StreamTradesRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{0}
}

func (x *StreamTradesRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type StreamBarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"` // e.g., "1Min", "5Min", "1Day"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBarsRequest) Reset() {
	*x = StreamBarsRequest{}
	mi := &file_marketdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBarsRequest) ProtoMessage() {}

func (x *StreamBarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBarsRequest.ProtoReflect.Descriptor instead.
func (*StreamBarsRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{1}
}

func (x *StreamBarsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *StreamBarsRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

type GetDailyBarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Market        string                 `protobuf:"bytes,4,opt,name=market,proto3" json:"market,omitempty"` // "us" or "cn"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyBarsRequest) Reset() {
	*x = GetDailyBarsRequest{}
	mi := &file_marketdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyBarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyBarsRequest) ProtoMessage() {}

func (x *GetDailyBarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyBarsRequest.ProtoReflect.Descriptor instead.
func (*GetDailyBarsRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{2}
}

func (x *GetDailyBarsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetDailyBarsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetDailyBarsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetDailyBarsRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

type GetDailyBarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bars          []*Bar                 `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyBarsResponse) Reset() {
	*x = GetDailyBarsResponse{}
	mi := &file_marketdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyBarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyBarsResponse) ProtoMessage() {}

func (x *GetDailyBarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyBarsResponse.ProtoReflect.Descriptor instead.
func (*GetDailyBarsResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{3}
}

func (x *GetDailyBarsResponse) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

type GetLatestQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestQuoteRequest) Reset() {
	*x = GetLatestQuoteRequest{}
	mi := &file_marketdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestQuoteRequest) ProtoMessage() {}

func (x *GetLatestQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetLatestQuoteRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestQuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Bar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Open          float64                `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,4,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,5,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,6,opt,name=close,proto3" json:"close,omitempty"`
	Volume        int64                  `protobuf:"varint,7,opt,name=volume,proto3" json:"volume,omitempty"`
	TradeCount    int64                  `protobuf:"varint,8,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`
	Vwap          float64                `protobuf:"fixed64,9,opt,name=vwap,proto3" json:"vwap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_marketdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{5}
}

func (x *Bar) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Bar) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Bar) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Bar) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Bar) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Bar) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Bar) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Bar) GetTradeCount() int64 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *Bar) GetVwap() float64 {
	if x != nil {
		return x.Vwap
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Exchange      string                 `protobuf:"bytes,5,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_marketdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{6}
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Trade) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Trade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Quote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BidPrice      float64                `protobuf:"fixed64,3,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	AskPrice      float64                `protobuf:"fixed64,4,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"`
	BidSize       int64                  `protobuf:"varint,5,opt,name=bid_size,json=bidSize,proto3" json:"bid_size,omitempty"`
	AskSize       int64                  `protobuf:"varint,6,opt,name=ask_size,json=askSize,proto3" json:"ask_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_marketdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{7}
}

func (x *Quote) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Quote) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Quote) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *Quote) GetAskPrice() float64 {
	if x != nil {
		return x.AskPrice
	}
	return 0
}

func (x *Quote) GetBidSize() int64 {
	if x != nil {
		return x.BidSize
	}
	return 0
}

func (x *Quote) GetAskSize() int64 {
	if x != nil {
		return x.AskSize
	}
	return 0
}

type StreamLiveTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExIndexOnly   bool                   `protobuf:"varint,1,opt,name=ex_index_only,json=exIndexOnly,proto3" json:"ex_index_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLiveTradesRequest) Reset() {
	*x = StreamLiveTradesRequest{}
	mi := &file_marketdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLiveTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLiveTradesRequest) ProtoMessage() {}

func (x *StreamLiveTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLiveTradesRequest.ProtoReflect.Descriptor instead.
func (*StreamLiveTradesRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{8}
}

func (x *StreamLiveTradesRequest) GetExIndexOnly() bool {
	if x != nil {
		return x.ExIndexOnly
	}
	return false
}

type LiveTrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix ms (ET)
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Exchange      string                 `protobuf:"bytes,5,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Conditions    string                 `protobuf:"bytes,7,opt,name=conditions,proto3" json:"conditions,omitempty"`
	IsIndex       bool                   `protobuf:"varint,8,opt,name=is_index,json=isIndex,proto3" json:"is_index,omitempty"`
	IsToday       bool                   `protobuf:"varint,9,opt,name=is_today,json=isToday,proto3" json:"is_today,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveTrade) Reset() {
	*x = LiveTrade{}
	mi := &file_marketdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveTrade) ProtoMessage() {}

func (x *LiveTrade) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveTrade.ProtoReflect.Descriptor instead.
func (*LiveTrade) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{9}
}

func (x *LiveTrade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *LiveTrade) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LiveTrade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *LiveTrade) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *LiveTrade) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *LiveTrade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LiveTrade) GetConditions() string {
	if x != nil {
		return x.Conditions
	}
	return ""
}

func (x *LiveTrade) GetIsIndex() bool {
	if x != nil {
		return x.IsIndex
	}
	return false
}

func (x *LiveTrade) GetIsToday() bool {
	if x != nil {
		return x.IsToday
	}
	return false
}

var File_marketdata_proto protoreflect.FileDescriptor

const file_marketdata_proto_rawDesc = "" +
	"\n" +
	"\x10marketdata.proto\x12\x12jupitor.marketdata\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n" +
	"\x13StreamTradesRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"K\n" +
	"\x11StreamBarsRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\"\xa5\x01\n" +
	"\x13GetDailyBarsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x16\n" +
	"\x06market\x18\x04 \x01(\tR\x06market\"C\n" +
	"\x14GetDailyBarsResponse\x12+\n" +
	"\x04bars\x18\x01 \x03(\v2\x17.jupitor.marketdata.BarR\x04bars\"/\n" +
	"\x15GetLatestQuoteRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xf4\x01\n" +
	"\x03Bar\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04open\x18\x03 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x04 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x06 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\a \x01(\x03R\x06volume\x12\x1f\n" +
	"\vtrade_count\x18\b \x01(\x03R\n" +
	"tradeCount\x12\x12\n" +
	"\x04vwap\x18\t \x01(\x01R\x04vwap\"\xaf\x01\n" +
	"\x05Trade\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\bexchange\x18\x05 \x01(\tR\bexchange\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\"\xc9\x01\n" +
	"\x05Quote\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tbid_price\x18\x03 \x01(\x01R\bbidPrice\x12\x1b\n" +
	"\task_price\x18\x04 \x01(\x01R\baskPrice\x12\x19\n" +
	"\bbid_size\x18\x05 \x01(\x03R\abidSize\x12\x19\n" +
	"\bask_size\x18\x06 \x01(\x03R\aaskSize\"=\n" +
	"\x17StreamLiveTradesRequest\x12\"\n" +
	"\rex_index_only\x18\x01 \x01(\bR\vexIndexOnly\"\xed\x01\n" +
	"\tLiveTrade\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\bexchange\x18\x05 \x01(\tR\bexchange\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"conditions\x18\a \x01(\tR\n" +
	"conditions\x12\x19\n" +
	"\bis_index\x18\b \x01(\bR\aisIndex\x12\x19\n" +
	"\bis_today\x18\t \x01(\bR\aisToday2\xcf\x03\n" +
	"\n" +
	"MarketData\x12T\n" +
	"\fStreamTrades\x12'.jupitor.marketdata.StreamTradesRequest\x1a\x19.jupitor.marketdata.Trade0\x01\x12N\n" +
	"\n" +
	"StreamBars\x12%.jupitor.marketdata.StreamBarsRequest\x1a\x17.jupitor.marketdata.Bar0\x01\x12a\n" +
	"\fGetDailyBars\x12'.jupitor.marketdata.GetDailyBarsRequest\x1a(.jupitor.marketdata.GetDailyBarsResponse\x12V\n" +
	"\x0eGetLatestQuote\x12).jupitor.marketdata.GetLatestQuoteRequest\x1a\x19.jupitor.marketdata.Quote\x12`\n" +
	"\x10StreamLiveTrades\x12+.jupitor.marketdata.StreamLiveTradesRequest\x1a\x1d.jupitor.marketdata.LiveTrade0\x01B\x19Z\x17jupitor/internal/api/pbb\x06proto3"

var (
	file_marketdata_proto_rawDescOnce sync.Once
	file_marketdata_proto_rawDescData []byte
)

func file_marketdata_proto_rawDescGZIP() []byte {
	file_marketdata_proto_rawDescOnce.Do(func() {
		file_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketdata_proto_rawDesc), len(file_marketdata_proto_rawDesc)))
	})
	return file_marketdata_proto_rawDescData
}

var file_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_marketdata_proto_goTypes = []any{
	(*StreamTradesRequest)(nil),     // 0: jupitor.marketdata.StreamTradesRequest
	(*StreamBarsRequest)(nil),       // 1: jupitor.marketdata.StreamBarsRequest
	(*GetDailyBarsRequest)(nil),     // 2: jupitor.marketdata.GetDailyBarsRequest
	(*GetDailyBarsResponse)(nil),    // 3: jupitor.marketdata.GetDailyBarsResponse
	(*GetLatestQuoteRequest)(nil),   // 4: jupitor.marketdata.GetLatestQuoteRequest
	(*Bar)(nil),                     // 5: jupitor.marketdata.Bar
	(*Trade)(nil),                   // 6: jupitor.marketdata.Trade
	(*Quote)(nil),                   // 7: jupitor.marketdata.Quote
	(*StreamLiveTradesRequest)(nil), // 8: jupitor.marketdata.StreamLiveTradesRequest
	(*LiveTrade)(nil),               // 9: jupitor.marketdata.LiveTrade
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_marketdata_proto_depIdxs = []int32{
	10, // 0: jupitor.marketdata.GetDailyBarsRequest.start:type_name -> google.protobuf.Timestamp
	10, // 1: jupitor.marketdata.GetDailyBarsRequest.end:type_name -> google.protobuf.Timestamp
	5,  // 2: jupitor.marketdata.GetDailyBarsResponse.bars:type_name -> jupitor.marketdata.Bar
	10, // 3: jupitor.marketdata.Bar.timestamp:type_name -> google.protobuf.Timestamp
	10, // 4: jupitor.marketdata.Trade.timestamp:type_name -> google.protobuf.Timestamp
	10, // 5: jupitor.marketdata.Quote.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: jupitor.marketdata.MarketData.StreamTrades:input_type -> jupitor.marketdata.StreamTradesRequest
	1,  // 7: jupitor.marketdata.MarketData.StreamBars:input_type -> jupitor.marketdata.StreamBarsRequest
	2,  // 8: jupitor.marketdata.MarketData.GetDailyBars:input_type -> jupitor.marketdata.GetDailyBarsRequest
	4,  // 9: jupitor.marketdata.MarketData.GetLatestQuote:input_type -> jupitor.marketdata.GetLatestQuoteRequest
	8,  // 10: jupitor.marketdata.MarketData.StreamLiveTrades:input_type -> jupitor.marketdata.StreamLiveTradesRequest
	6,  // 11: jupitor.marketdata.MarketData.StreamTrades:output_type -> jupitor.marketdata.Trade
	5,  // 12: jupitor.marketdata.MarketData.StreamBars:output_type -> jupitor.marketdata.Bar
	3,  // 13: jupitor.marketdata.MarketData.GetDailyBars:output_type -> jupitor.marketdata.GetDailyBarsResponse
	7,  // 14: jupitor.marketdata.MarketData.GetLatestQuote:output_type -> jupitor.marketdata.Quote
	9,  // 15: jupitor.marketdata.MarketData.StreamLiveTrades:output_type -> jupitor.marketdata.LiveTrade
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_marketdata_proto_init() }
func file_marketdata_proto_init() {
	if File_marketdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketdata_proto_rawDesc), len(file_marketdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketdata_proto_goTypes,
		DependencyIndexes: file_marketdata_proto_depIdxs,
		MessageInfos:      file_marketdata_proto_msgTypes,
	}.Build()
	File_marketdata_proto = out.File
	file_marketdata_proto_goTypes = nil
	file_marketdata_proto_depIdxs = nil
}
