// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: marketdata.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketData_StreamTrades_FullMethodName     = "/jupitor.marketdata.MarketData/StreamTrades"
	MarketData_StreamBars_FullMethodName       = "/jupitor.marketdata.MarketData/StreamBars"
	MarketData_GetDailyBars_FullMethodName     = "/jupitor.marketdata.MarketData/GetDailyBars"
	MarketData_GetLatestQuote_FullMethodName   = "/jupitor.marketdata.MarketData/GetLatestQuote"
	MarketData_StreamLiveTrades_FullMethodName = "/jupitor.marketdata.MarketData/StreamLiveTrades"
)

// MarketDataClient is the client API for MarketData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketData service provides real-time and historical market data.
type MarketDataClient interface {
	// Subscribe to live trade updates for given symbols.
	StreamTrades(ctx context.Context, in *StreamTradesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Trade], error)
	// Subscribe to live bar updates for given symbols.
	StreamBars(ctx context.Context, in *StreamBarsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Bar], error)
	// Get historical daily bars.
	GetDailyBars(ctx context.Context, in *GetDailyBarsRequest, opts ...grpc.CallOption) (*GetDailyBarsResponse, error)
	// Get latest quote for a symbol.
	GetLatestQuote(ctx context.Context, in *GetLatestQuoteRequest, opts ...grpc.CallOption) (*Quote, error)
	// Stream live stock trades (snapshot + live updates).
	StreamLiveTrades(ctx context.Context, in *StreamLiveTradesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LiveTrade], error)
}

type marketDataClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataClient(cc grpc.ClientConnInterface) MarketDataClient {
	return &marketDataClient{cc}
}

func (c *marketDataClient) StreamTrades(ctx context.Context, in *StreamTradesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Trade], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketData_ServiceDesc.Streams[0], MarketData_StreamTrades_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTradesRequest, Trade]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketData_StreamTradesClient = grpc.ServerStreamingClient[Trade]

func (c *marketDataClient) StreamBars(ctx context.Context, in *StreamBarsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Bar], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketData_ServiceDesc.Streams[1], MarketData_StreamBars_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBarsRequest, Bar]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketData_StreamBarsClient = grpc.ServerStreamingClient[Bar]

func (c *marketDataClient) GetDailyBars(ctx context.Context, in *GetDailyBarsRequest, opts ...grpc.CallOption) (*GetDailyBarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyBarsResponse)
	err := c.cc.Invoke(ctx, MarketData_GetDailyBars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataClient) GetLatestQuote(ctx context.Context, in *GetLatestQuoteRequest, opts ...grpc.CallOption) (*Quote, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Quote)
	err := c.cc.Invoke(ctx, MarketData_GetLatestQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataClient) StreamLiveTrades(ctx context.Context, in *StreamLiveTradesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LiveTrade], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketData_ServiceDesc.Streams[2], MarketData_StreamLiveTrades_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLiveTradesRequest, LiveTrade]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketData_StreamLiveTradesClient = grpc.ServerStreamingClient[LiveTrade]

// MarketDataServer is the server API for MarketData service.
// All implementations must embed UnimplementedMarketDataServer
// for forward compatibility.
//
// MarketData service provides real-time and historical market data.
type MarketDataServer interface {
	// Subscribe to live trade updates for given symbols.
	StreamTrades(*StreamTradesRequest, grpc.ServerStreamingServer[Trade]) error
	// Subscribe to live bar updates for given symbols.
	StreamBars(*StreamBarsRequest, grpc.ServerStreamingServer[Bar]) error
	// Get historical daily bars.
	GetDailyBars(context.Context, *GetDailyBarsRequest) (*GetDailyBarsResponse, error)
	// Get latest quote for a symbol.
	GetLatestQuote(context.Context, *GetLatestQuoteRequest) (*Quote, error)
	// Stream live stock trades (snapshot + live updates).
	StreamLiveTrades(*StreamLiveTradesRequest, grpc.ServerStreamingServer[LiveTrade]) error
	mustEmbedUnimplementedMarketDataServer()
}

// UnimplementedMarketDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketDataServer struct{}

func (UnimplementedMarketDataServer) StreamTrades(*StreamTradesRequest, grpc.ServerStreamingServer[Trade]) error {
	return status.Error(codes.Unimplemented, "method StreamTrades not implemented")
}
func (UnimplementedMarketDataServer) StreamBars(*StreamBarsRequest, grpc.ServerStreamingServer[Bar]) error {
	return status.Error(codes.Unimplemented, "method StreamBars not implemented")
}
func (UnimplementedMarketDataServer) GetDailyBars(context.Context, *GetDailyBarsRequest) (*GetDailyBarsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyBars not implemented")
}
func (UnimplementedMarketDataServer) GetLatestQuote(context.Context, *GetLatestQuoteRequest) (*Quote, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestQuote not implemented")
}
func (UnimplementedMarketDataServer) StreamLiveTrades(*StreamLiveTradesRequest, grpc.ServerStreamingServer[LiveTrade]) error {
	return status.Error(codes.Unimplemented, "method StreamLiveTrades not implemented")
}
func (UnimplementedMarketDataServer) mustEmbedUnimplementedMarketDataServer() {}
func (UnimplementedMarketDataServer) testEmbeddedByValue()                    {}

// UnsafeMarketDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServer will
// result in compilation errors.
type UnsafeMarketDataServer interface {
	mustEmbedUnimplementedMarketDataServer()
}

func RegisterMarketDataServer(s grpc.ServiceRegistrar, srv MarketDataServer) {
	// If the following call panics, it indicates UnimplementedMarketDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketData_ServiceDesc, srv)
}

func _MarketData_StreamTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTradesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServer).StreamTrades(m, &grpc.GenericServerStream[StreamTradesRequest, Trade]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketData_StreamTradesServer = grpc.ServerStreamingServer[Trade]

func _MarketData_StreamBars_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBarsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServer).StreamBars(m, &grpc.GenericServerStream[StreamBarsRequest, Bar]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketData_StreamBarsServer = grpc.ServerStreamingServer[Bar]

func _MarketData_GetDailyBars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyBarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServer).GetDailyBars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketData_GetDailyBars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServer).GetDailyBars(ctx, req.(*GetDailyBarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketData_GetLatestQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServer).GetLatestQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketData_GetLatestQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServer).GetLatestQuote(ctx, req.(*GetLatestQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketData_StreamLiveTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLiveTradesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServer).StreamLiveTrades(m, &grpc.GenericServerStream[StreamLiveTradesRequest, LiveTrade]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketData_StreamLiveTradesServer = grpc.ServerStreamingServer[LiveTrade]

// MarketData_ServiceDesc is the grpc.ServiceDesc for MarketData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jupitor.marketdata.MarketData",
	HandlerType: (*MarketDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailyBars",
			Handler:    _MarketData_GetDailyBars_Handler,
		},
		{
			MethodName: "GetLatestQuote",
			Handler:    _MarketData_GetLatestQuote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTrades",
			Handler:       _MarketData_StreamTrades_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBars",
			Handler:       _MarketData_StreamBars_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLiveTrades",
			Handler:       _MarketData_StreamLiveTrades_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "marketdata.proto",
}
