package domain

import "time"

// ---------------------------------------------------------------------------
// Enum types
// ---------------------------------------------------------------------------

// OrderSide represents the side of an order (buy or sell).
type OrderSide string

const (
	OrderSideBuy  OrderSide = "buy"
	OrderSideSell OrderSide = "sell"
)

// OrderType represents the execution type of an order.
type OrderType string

const (
	OrderTypeMarket    OrderType = "market"
	OrderTypeLimit     OrderType = "limit"
	OrderTypeStop      OrderType = "stop"
	OrderTypeStopLimit OrderType = "stop_limit"
)

// OrderStatus represents the lifecycle status of an order.
type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusSubmitted OrderStatus = "submitted"
	OrderStatusFilled    OrderStatus = "filled"
	OrderStatusPartial   OrderStatus = "partial"
	OrderStatusCancelled OrderStatus = "cancelled"
	OrderStatusRejected  OrderStatus = "rejected"
)

// TimeInForce specifies how long an order remains active.
type TimeInForce string

const (
	TimeInForceDay TimeInForce = "day"
	TimeInForceGTC TimeInForce = "gtc"
	TimeInForceIOC TimeInForce = "ioc"
	TimeInForceFOK TimeInForce = "fok"
)

// PositionSide indicates whether a position is long or short.
type PositionSide string

const (
	PositionSideLong  PositionSide = "long"
	PositionSideShort PositionSide = "short"
)

// SignalType represents the type of trading signal.
type SignalType string

const (
	SignalTypeBuy  SignalType = "buy"
	SignalTypeSell SignalType = "sell"
	SignalTypeHold SignalType = "hold"
)

// Market represents the market geography.
type Market string

const (
	MarketUS Market = "us"
	MarketCN Market = "cn"
)

// ---------------------------------------------------------------------------
// Core domain structs
// ---------------------------------------------------------------------------

// Bar represents an OHLCV price bar for a given symbol and time period.
type Bar struct {
	Symbol     string
	Timestamp  time.Time
	Open       float64
	High       float64
	Low        float64
	Close      float64
	Volume     int64
	TradeCount int64
	VWAP       float64
}

// Trade represents a single executed trade on an exchange.
type Trade struct {
	Symbol     string
	Timestamp  time.Time
	Price      float64
	Size       int64
	Exchange   string
	ID         string
	Conditions string // comma-joined condition codes
	Update     string // update type (empty for normal trades)
}

// Quote represents a bid/ask quote for a symbol at a point in time.
type Quote struct {
	Symbol   string
	Timestamp time.Time
	BidPrice float64
	AskPrice float64
	BidSize  int64
	AskSize  int64
}

// Order represents a trading order submitted to a broker.
type Order struct {
	ID             string
	Symbol         string
	Side           OrderSide
	Type           OrderType
	TimeInForce    TimeInForce
	Qty            float64
	LimitPrice     float64
	StopPrice      float64
	Status         OrderStatus
	FilledQty      float64
	FilledAvgPrice float64
	StrategyID     string
	BrokerOrderID  string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Position represents a current holding in a symbol.
type Position struct {
	Symbol          string
	Qty             float64
	AvgEntryPrice   float64
	MarketValue     float64
	UnrealizedPL    float64
	UnrealizedPLPct float64
	Side            PositionSide
	OpenedAt        time.Time
	UpdatedAt       time.Time
}

// Signal represents a trading signal generated by a strategy.
type Signal struct {
	ID         int64
	StrategyID string
	Symbol     string
	Type       SignalType
	Strength   float64
	Metadata   map[string]string
	CreatedAt  time.Time
}

// Asset represents a tradeable financial instrument.
type Asset struct {
	Symbol     string
	Name       string
	Exchange   string
	Market     string // "us" or "cn"
	AssetClass string
}

// AccountInfo holds a snapshot of account-level financial metrics.
type AccountInfo struct {
	Equity         float64
	Cash           float64
	BuyingPower    float64
	PortfolioValue float64
	DailyPL        float64
	DailyPLPct     float64
}
